name: iem_app
description: Intelligent Electricity Meter App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  # Flutter SDK and packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http:
  intl: 0.18.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  http_parser: ^4.0.0
  path_provider: ^2.1.0
  lottie:
  cached_network_image:
  photo_view:
  flutter_app_badger:
  package_info:


flutter_icons:
  android: false. // I already had android icons
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/logo-no-background.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/app_setting_json.json
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Poppins #english font
      fonts:
        - asset: assets/fonts/eng_fonts/Poppins-Black.ttf
        - asset: assets/fonts/eng_fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-Bold.ttf
        - asset: assets/fonts/eng_fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/eng_fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/eng_fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-Italic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-Light.ttf
        - asset: assets/fonts/eng_fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-Medium.ttf
        #        - weight : 500
        - asset: assets/fonts/eng_fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-Regular.ttf
        #        - weight : 400
        - asset: assets/fonts/eng_fonts/Poppins-SemiBold.ttf
        #        - weight : 600
        - asset: assets/fonts/eng_fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/eng_fonts/Poppins-Thin.ttf
        - asset: assets/fonts/eng_fonts/Poppins-ThinItalic.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf