// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB5meOSAPP-AkHqZnrusWdhM6c4WZcN7VM',
//     appId: '1:599882398366:web:04cb6edc3ba244b564d98f',
//     messagingSenderId: '599882398366',
//     projectId: 'wfimobileapp',
//     authDomain: 'wfimobileapp.firebaseapp.com',
//     storageBucket: 'wfimobileapp.appspot.com',
//     measurementId: 'G-L0MBK91ZN1',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAykf2kOfKYT3L2ungcI2VdXvv_c9821Wo',
//     appId: '1:599882398366:android:d694f30248f3dd5964d98f',
//     messagingSenderId: '599882398366',
//     projectId: 'wfimobileapp',
//     storageBucket: 'wfimobileapp.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA8uEDRiALzrpezSVCBZu6aeifKGSZgeMI',
//     appId: '1:599882398366:ios:d7603861f60113fe64d98f',
//     messagingSenderId: '599882398366',
//     projectId: 'wfimobileapp',
//     storageBucket: 'wfimobileapp.appspot.com',
//     androidClientId: '599882398366-4gjcef5dcp6c4re61bhkgmimkdthid3q.apps.googleusercontent.com',
//     iosClientId: '599882398366-ev1imuluhiar9f6o7kmavj9fns2t536v.apps.googleusercontent.com',
//     iosBundleId: 'watan.app.wfi',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA8uEDRiALzrpezSVCBZu6aeifKGSZgeMI',
//     appId: '1:599882398366:ios:d7603861f60113fe64d98f',
//     messagingSenderId: '599882398366',
//     projectId: 'wfimobileapp',
//     storageBucket: 'wfimobileapp.appspot.com',
//     androidClientId: '599882398366-4gjcef5dcp6c4re61bhkgmimkdthid3q.apps.googleusercontent.com',
//     iosClientId: '599882398366-ev1imuluhiar9f6o7kmavj9fns2t536v.apps.googleusercontent.com',
//     iosBundleId: 'watan.app.wfi',
//   );
// }
